### ISSUE TITLE
Updating project?

### ISSUE THREAD

**Issue by bumTomica** [n0nick/docker-clipperz-nginx#1]
Hello,,

Any plans on updating this project to work with current version of Clipperz & Docker? Curently it breaks on "_sudo docker build -t="docker-clipperz-nginx" ._" command with this error:

`An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build\?buildargs\=%7B%7D\&cgroupparent\=\&cpuperiod\=0\&cpuquota\=0\&cpusetcpus\=\&cpusetmems\=\&cpushares\=0\&dockerfile\=Dockerfile\&labels\=%7B%7D\&memory\=0\&memswap\=0\&rm\=1\&shmsize\=0\&t\=docker-clipperz-nginx\&ulimits\=null: open //./pipe/docker_engine: The system cannot find the file specified.`

Thanks!

**Comment by n0nick** [comment]
I'm sorry about that. I created this Dockerfile for a personal use but has since stopped using Clipperz in this particular scenario.
I'm not sure I'll have time soon to look into the issue with this Dockerfile - but feel free to submit a pull request if you find the fix.
Sorry again!

**Comment by n0nick** [comment]
Also, I'm not sure the error you're getting is with this project's particular `Dockerfile`, since it seems to revolve around a `./pipe/docker_engine` file which is not referenced in this project.
